namespace Reporting.Function.Constant
{
    public static class ErrorMessage
    {
        public const string ERROR_PROCESS_FAILED_CANNOT_CONVERT = "ERROR.GENERIC.PROCESS_FAILED.CANNOT_CONVERT";
        public const string COMMON_ERROR_NO_TEMPLATE = "ERROR.SYSTEM.NOT_SUPPORTED.NO_TEMPLATE";

        public const string COMMON_ERROR_MISSED_CONFIG_CLIENT_ID = "ERROR.GENERIC.PROCESS_FAILED.MISSED_CONFIG.CLIENT_ID";
        public const string COMMON_ERROR_MISSED_CONFIG_CLIENT_SECRET = "ERROR.GENERIC.PROCESS_FAILED.MISSED_CONFIG.CLIENT_SECRET";
        public const string COMMON_ERROR_INVALID_SHEET_FORMAT = "Invalid sheet format. Some fields may be misssing.";
        public const string ERROR_STORAGE_MEDIA_EXISTED = "STORAGE.MEDIA.EXISTED";
        public const string ERROR_IMPORT_TEMPLATE_ZIP_CONTENT = "ERROR.TEMPLATE.IMPORT.INVALID_ZIP_CONTENT";

        public const string GENERAL_INVALID_VALUE = "AUDIT.LOG.IMPORT_ERROR.GENERAL_INVALID";
        public const string GREATER_THAN_MAX_VALUE = "AUDIT.LOG.IMPORT_ERROR.GREATER_THAN_MAX_VALUE";
    }

}
