namespace Reporting.Function.Constant
{
    public static class ErrorCode
    {
        public const string ERROR_ENTITY_INVALID = "ERROR.ENTITY.INVALID";
        public const string FAILED_WHILE_CONNECTING_TO_DB = "ERROR.CONNECT_TO_DB_FAILED";
        public const string NO_REPORT_MATCH = "REPORT.REPORT.NO_REPORT_MATCH";
        public const string FAILED_WHILE_GETTING_TOKEN_FROM_NATIVE_STORAGE = "REPORT.REPORT.GET_TOKEN_FAILED_FROM_NATIVE_STORAGE";
        public const string FAILED_WHILE_UPLOADING_FILE_TO_NATIVE_STORAGE = "REPORT.REPORT.UPLOAD_FAILED_TO_NATIVE_STORAGE";
        public const string FAILED_WHILE_DOWNLOADING_FILE_FROM_NATIVE_STORAGE = "REPORT.REPORT.DOWNLOAD_FAILED_FROM_NATIVE_STORAGE";
        public const string FAILED_WHILE_DOWNLOADING_FILE_FROM_AZURE_BLOB_STORAGE = "REPORT.REPORT.DOWNLOAD_FAILED_FROM_AZURE_BLOB_STORAGE";
    }
}