resources:
  repositories:
  - repository: PipelineTemplateServiceRepository
    endpoint: GitServiceAcconnection
    type: git
    name: AHI Pipeline Template/pipeline-template-service
    ref: master
  - repository: HelmChartRepository
    endpoint: GitServiceAcconnection
    type: git
    name: Asset DevOps - Helm/helm-chart
    ref: sandbox

trigger:
  branches:
    include:
    - features/*/develop
    - master
  paths:
    include:
    - src/*
    - tests/*
    - sql/*

pool:
  name: 'DXP Hosted BE'

parameters:
  - name: Platform
    displayName: Platform
    type: string
    default: 'Azure'
    values:
      - 'All'
      - 'Azure'
      - 'AWS'
      - 'Alibaba'
  - name: DockerFile
    displayName: DockerFile
    type: string
    default: 'Dockerfile-migration'

stages:
- template: migration-build-templates.yml@PipelineTemplateServiceRepository
  parameters:
    Platform: ${{ parameters.Platform }}
    DockerFile: ${{ parameters.DockerFile }}
    ServiceName: 'reporting-service-vnext'
    ConnectionString: '--connectionstring=Server=db;Database=reporting_34e5ee62429c4724b3d03891bd0a08c9;User=sa;Password=Pass1234!;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;'
    DatabaseType: 'sqlserver'